[platformio]
default_envs = esp32dev, nodemcuv2

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
lib_extra_dirs = ../..

[env:esp32dev]
platform = espressif32
board = esp32dev

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
